name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd projects/csc648-fa25-0104-team15
            git reset --hard HEAD  # Reset any local changes
            git pull origin main
            # Restart services if needed (e.g., Node, Flask, Apache, etc.)
            # Example: sudo systemctl restart my-service
            sudo systemctl restart flask_app
